### ISSUE TITLE
Upgrade `lapin-futures`

### ISSUE THREAD

**Issue by khuey** [sozu-proxy/lapin-futures-tls#13]
Not sure how actively this is maintained, any chance of getting an upgraded version of `lapin-futures` in here soon? I see that its API has changed quite a bit :/

**Comment by Keruspe** [comment]
Lapin-futures now has built in TLS support, this is why this crate is no
longer updated

**Comment by khuey** [comment]
Ah, thanks. It might be helpful to post a deprecation message on crates.io then.
